ALTER TABLE ohlc_1_min ADD COLUMN value bigint NOT NULL DEFAULT 0;
ALTER TABLE ohlc_5_min ADD COLUMN value bigint NOT NULL DEFAULT 0;
ALTER TABLE ohlc_10_min ADD COLUMN value bigint NOT NULL DEFAULT 0;
ALTER TABLE ohlc_15_min ADD COLUMN value bigint NOT NULL DEFAULT 0;
ALTER TABLE ohlc_30_min ADD COLUMN value bigint NOT NULL DEFAULT 0;
ALTER TABLE ohlc_1_hour ADD COLUMN value bigint NOT NULL DEFAULT 0;
ALTER TABLE ohlc_1_day ADD COLUMN value bigint NOT NULL DEFAULT 0;
