
--
-- Data for Name: client_webwidget_columns; Type: TABLE DATA; Schema: ${webmaster}; Owner: mutrade
--
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'Market', 'x["market_id"]', 1, 0, 0, 1, 1, 1, 1, 10);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'Instrument Type', 'x["instrument_type"]', 1, 1, 1, 12, 1, 1, 1, 20);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'Security Id', 'x["security_id"]', 0, 2, 2, 0, 1, 1, 1, 30);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'Symbol', 'x["symbol"]', 1, 3, 3, 0, 1, 1, 1, 40);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'Group Name', 'x["group_name"]', 1, 4, 4, 0, 1, 1, 1, 50);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'Bid Qty', 'x["bq0"]', 4, 5, 5, 0, 1, 1, 1, 60);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'Bid Price', 'x["bp0"]', 3, 6, 6, 0, 1, 1, 1, 70);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'Ask Price', 'x["ap0"]', 3, 7, 7, 0, 1, 1, 1, 80);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'Ask Qty', 'x["aq0"]', 4, 8, 8, 0, 1, 1, 1, 90);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'LTP', 'x["13"]', 3, 9, 9, 0, 1, 1, 1, 100);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'Last Trade Qty', 'x["12"]', 4, 10, 10, 0, 1, 1, 1, 110);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, '% Change', '', 5, 11, 11, 0, 0, 1, 1, 120);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'Open Price', 'x["16"]', 3, 13, 13, 0, 1, 1, 1, 140);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'High Price', 'x["18"]', 3, 14, 14, 0, 1, 1, 1, 150);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'Low Price', 'x["19"]', 3, 15, 15, 0, 1, 1, 1, 160);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'Close Price', 'x["17"]', 3, 16, 16, 0, 1, 1, 1, 170);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, '52 W High', 'x["hi_52_wk"]', 3, 17, 17, 0, 1, 1, 1, 180);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, '52 W Low', 'x["lo_52_wk"]', 3, 18, 18, 0, 1, 1, 1, 190);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'Volume', 'x["6"]', 4, 21, 21, 0, 1, 1, 1, 220);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'Value', 'x["7"]', 3, 22, 22, 0, 1, 1, 1, 230);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'Trend', 'x["9"]', 1, 23, 23, 0, 1, 1, 1, 240);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'OI Qty', 'cq.oi_qty', 4, 24, 24, 0, 0, 1, 1, 250);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'OI Change', 'cq.oi_change', 5, 26, 26, 0, 0, 1, 1, 270);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'Total Bid Qty', 'x["20"]', 4, 29, 29, 0, 1, 1, 1, 300);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'Total Ask Qty', 'x["21"]', 4, 30, 30, 0, 1, 1, 1, 310);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'Total Traded Qty', 'x["5"]', 4, 31, 31, 0, 1, 1, 1, 320);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'Precision', 'x["scrip_precision"]', 0, 33, 33, 0, 1, 0, 0, 340);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'expiryyearmon', 'x["maturity_yearmon"]', 0, 35, 35, 0, 1, 0, 0, 360);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'Strike Price', 'x["strike_price"]', 3, 36, 36, 0, 1, 0, 1, 370);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'lotsize', 'x["market_lot"]', 0, 38, 38, 0, 1, 0, 0, 390);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'Market Name', 'x["display_name"]', 1, 39, 39, 0, 1, 1, 1, 11);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'Security Name', 'x["scrip_name"]', 1, 41, 41, 0, 1, 1, 1, 400);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'Suspended', 'x["suspended"]', 1, 42, 42, 0, 1, 0, 0, 410);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'Curreny Flag', 'x["is_currency"]', 0, 46, 46, 0, 1, 0, 0, 450);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'Maturity Date', 'x["issue_maturity_date"]', 2, 49, 49, 0, 1, 0, 1, 55);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'Lower Ckt Limit', 'x["22"]', 3, 20, 20, 0, 1, 1, 1, 210);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'Upper Ckt Limit', 'x["23"]', 3, 19, 19, 0, 1, 1, 1, 200);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'OI Value', 'cq.oi_value', 3, 25, 25, 0, 0, 1, 0, 260);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'Avg Ask Price', 'x["aa0"]', 3, 27, 27, 0, 1, 1, 0, 280);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'Change In Price', '(x["13"] or 0) - (x["17"] or 0)', 3, 12, 12, 0, 1, 1, 1, 130);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'ISIN', 'x["isin"]', 1, 60, 60, 0, 1, 0, 1, 460);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'Avg trade price', 'x["24"]', 3, 62, 62, 0, 1, 1, 1, 480);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'Avg Bid Price', 'x["ba0"]', 3, 28, 28, 0, 1, 1, 0, 290);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'Expiry Date', '(str(x["maturity_day"]) if x["maturity_day"] else "") +((str("/") + str(x["maturity_yearmon"])[4:] + str("/")+str(x["maturity_yearmon"])[:-2]) if x["maturity_yearmon"] else "")', 0, 34, 34, 0, 1, 0, 1, 350);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'Option Type', '(x["option_type"] or "")+(x["option_attribute"] or "")', 0, 37, 37, 0, 1, 0, 1, 380);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 0, 'QtyPrecision', 'x["qty_precision"]', 0, 67, 67, 0, 1, 0, 0, 510);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 1, 'Market', 'x._marketId', 1, 0, 0, 1, 1, 1, 1, 10);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 1, 'Security ID', 'x._securityId', 0, 1, 1, 0, 1, 0, 1, 20);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 1, 'Instrument Type', 'x._securityType', 0, 2, 2, 2, 1, 1, 1, 30);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 1, 'Client ID', 'x._id', 1, 3, 3, 17, 1, 1, 1, 31);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 1, 'Product', 'x._productType', 1, 4, 4, 6, 1, 1, 1, 40);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 1, 'Symbol', 'y["symbol"]', 1, 5, 5, 13, 1, 1, 1, 50);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 1, 'Series', 'y["series"]', 1, 6, 6, 0, 1, 0, 1, 60);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 1, 'ScripPrecision', 'y["precision"]', 0, 15, 15, 0, 1, 0, 0, 150);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 1, 'Sell Amount', 'x.sellTurnOverInQuoteCurrency', 3, 12, 12, 0, 1, 0, 1, 120);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 1, 'Buy Amount', 'x.buyTurnOverInQuoteCurrency', 3, 9, 9, 0, 1, 0, 1, 90);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 1, 'Avg Buy Price', 'x.avgBuyPriceInQuoteCurrency', 3, 8, 8, 0, 1, 0, 1, 80);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 1, 'Avg Sell Price', 'x.avgSellPriceInQuoteCurrency', 3, 11, 11, 0, 1, 0, 1, 110);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 1, 'Buy Qty', 'x._buyQuantity', 4, 7, 7, 0, 1, 0, 1, 70);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 1, 'Sell Qty', 'x._sellQuantity', 4, 10, 10, 0, 1, 0, 1, 100);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 1, 'currency flag', 'y["isCurrency"]', 3, 25, 25, 0, 1, 0, 0, 240);

insert into ${webmaster}.client_webwidget_columns ( widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) values ( 1, 1, 'Parent Cl Code', 'x.parentClCode', 1,26,26,0,1,0,1,260);

insert into ${webmaster}.client_webwidget_columns ( widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) values (1, 1, 'Child Cl Code', 'x.childClCode', 1,27,27,0,1,0,1,270);

insert into ${webmaster}.client_webwidget_columns ( widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) values (1, 1, 'Buy Lots', 'x.buyLots', 1,28,28,0,1,0,1,280);

insert into ${webmaster}.client_webwidget_columns ( widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) values (1, 1, 'Sell Lots', 'x.sellLots', 1,29,29,0,1,0,1,290);

insert into ${webmaster}.client_webwidget_columns ( widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) values (1, 1, 'Net Qty', 'x.netQty', 1,30,30,0,1,0,1,300);

insert into ${webmaster}.client_webwidget_columns ( widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) values (1, 1, 'Net Lots', 'x.netLots', 1,31,31,0,1,0,1,310);

insert into ${webmaster}.client_webwidget_columns ( widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) values(1, 1, 'Net Price', 'x.netPrice', 3,32,32,0,1,0,1,320);

insert into ${webmaster}.client_webwidget_columns ( widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) values (1, 1, 'Net Value', 'x.netValue', 3,33,33,0,1,0,1,330);

insert into ${webmaster}.client_webwidget_columns ( widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) values (1, 1, 'Ltp', 'x.ltp', 3,34,34,0,1,0,1,340);

insert into ${webmaster}.client_webwidget_columns ( widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) values (1, 1, 'M2M P/L', 'x.mtm', 1,35,35,0,1,0,1,350);

insert into ${webmaster}.client_webwidget_columns ( widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) values (1, 1, 'Booked P/L', 'x.bookedPL', 1,36,36,0,1,0,1,360);

insert into ${webmaster}.client_webwidget_columns ( widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) values (1, 1, 'Net P/L', 'x.netPL', 1,37,37,0,1,0,1,370);



INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 2, 'Order ID', 'x._orderId', 0, 0, 0, 0, 1, 0, 1, 10);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 2, 'Exchange Order ID', 'x._exchangeOrderId', 1, 1, 1, 0, 1, 0, 1, 20);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 2, 'Order Status', 'x._orderStatus', 0, 2, 2, 5, 1, 1, 1, 30);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 2, 'Market', 'x._marketType', 1, 3, 3, 1, 1, 1, 1, 40);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 2, 'Instrument Type', 'x._securityType', 0, 4, 4, 2, 1, 1, 1, 50);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 2, 'Product', 'x._productType', 1, 5, 5, 6, 1, 1, 1, 60);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 2, 'Symbol', 'y.scripName', 1, 6, 6, 13, 1, 1, 1, 70);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 2, 'Client ID', 'x._clientId', 1, 7, 7, 17, 1, 1, 1, 71);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 2, 'Series', 'x._series', 1, 8, 8, 0, 1, 0, 1, 80);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 2, 'Buy Sell', 'x._orderMode', 0, 9, 9, 8, 1, 1, 1, 90);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 2, 'Qty', 'x._quantity', 4, 10, 10, 0, 1, 0, 1, 100);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 2, 'Order Type', 'x._orderType', 0, 11, 11, 7, 1, 1, 1, 110);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 2, 'Price', 'x._price', 3, 12, 12, 0, 1, 0, 1, 120);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 2, 'Validity', 'x._orderValidity', 1, 14, 14, 9, 1, 0, 1, 140);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 2, 'Stop Price', 'x._stopPrice', 3, 15, 15, 0, 1, 0, 1, 150);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 2, 'Market To Limit', 'x._marketToLimitConversion', 1, 18, 18, 11, 1, 0, 1, 180);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 2, 'Filled Qty', 'x._filledQuantity', 4, 19, 19, 0, 1, 0, 1, 190);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 2, 'Last Filled Qty', 'x._lastFillQuantity', 4, 21, 21, 0, 1, 0, 1, 210);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 2, 'Last Filled Price', 'x._lastFillPrice', 3, 22, 22, 0, 1, 0, 1, 220);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 2, 'Pending Qty', 'x._quantity-x._filledQuantity', 4, 23, 23, 0, 1, 0, 1, 230);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 2, 'Original Order ID', 'x._origOrderId', 0, 24, 24, 0, 1, 0, 1, 240);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 2, 'Triggered Status', 'x._isTriggered', 1, 17, 17, 11, 1, 0, 1, 165);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 2, 'Time', 'x._exchModifyTime', 2, 26, 26, 0, 1, 0, 1, 260);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 2, 'Messages', 'x._rejectionText', 1, 27, 27, 0, 1, 0, 1, 270);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 2, 'ScripPrecision', 'y.scripPrecision', 0, 28, 28, 0, 1, 0, 0, 280);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 2, 'SecurityId', 'x._securityId', 0, 29, 29, 0, 1, 0, 0, 290);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 2, 'Placed By', 'x._userId', 1, 33, 33, 18, 1, 1, 1, 330);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 2, 'GTD Expiry', 'x.gtdExpiry', 1, 15, 15, 0, 1, 0, 1, 145);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 2, 'currency flag', 'y.isCurrency', 3, 37, 37, 0, 1, 0, 0, 170);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 2, 'Investor Pin', 'x._investorPin', 17, 36, 36, 17, 1, 0, 0, 335);

insert into ${webmaster}.client_webwidget_columns ( widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) values ( 1,2,'Strategy Id', 'x.strategyId', 1, 39, 39, 0, 1, 0 ,1, 390);

insert into ${webmaster}.client_webwidget_columns ( widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) values ( 1,2,'Trade Id', 'x.tradeId', 1, 40, 40, 0, 1, 0 ,1, 400);

insert into ${webmaster}.client_webwidget_columns ( widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) values (1,2,'Order Category', 'x.orderCategory', 1, 41, 41, 0, 1, 0 ,1, 410);

insert into ${webmaster}.client_webwidget_columns ( widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) values ( 1,2,'Parent Cl Code', 'x.parentClCode', 1, 42, 42, 0, 1, 0 ,1, 420);

insert into ${webmaster}.client_webwidget_columns ( widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) values ( 1,2,'Child Cl Code', 'x.childClCode', 1, 43, 43, 0, 1, 0 ,1, 430);

insert into ${webmaster}.client_webwidget_columns ( widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) values ( 1,2,'Part Code', 'x.partCode', 1, 44, 44, 0, 1, 0 ,1, 440);

INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 3, 'Order ID', 'x._orderId', 0, 0, 0, 0, 1, 0, 1, 10);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 3, 'Exchange Order ID', 'x._exchangeOrderId', 1, 1, 1, 0, 1, 0, 1, 20);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 3, 'Exchange Trade ID', 'x._execId', 1, 2, 2, 0, 1, 0, 1, 30);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 3, 'Client ID', 'x._clientId', 1, 3, 3, 17, 1, 1, 1, 31);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 3, 'Market', 'x._marketType', 1, 4, 4, 1, 1, 1, 1, 40);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 3, 'Instrument Type', 'x._securityType', 0, 5, 5, 2, 1, 1, 1, 50);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 3, 'Product', 'x._productType', 1, 6, 6, 6, 1, 1, 1, 60);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 3, 'Symbol', 'y.scripName', 1, 7, 7, 13, 1, 1, 1, 70);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 3, 'Series', 'x._series', 1, 8, 8, 0, 1, 0, 1, 80);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 3, 'Buy Sell', 'x._orderMode', 0, 9, 9, 8, 1, 1, 1, 90);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 3, 'Filled Qty', 'x._lastFillQuantity', 4, 10, 10, 0, 1, 0, 1, 100);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 3, 'Filled Price', 'x._lastFillPrice', 3, 11, 11, 0, 1, 0, 1, 110);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 3, 'Trade Time', 'x._lastTradeTime', 2, 13, 13, 0, 1, 0, 1, 130);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 3, 'ScripPrecision', 'y.scripPrecision', 0, 14, 14, 0, 1, 0, 0, 140);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 3, 'Placed By', 'x._userId', 1, 18, 18, 18, 1, 1, 1, 180);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 3, 'currency flag', 'y.isCurrency', 3, 39, 39, 0, 1, 0, 0, 260);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 3, 'Investor Pin', 'x._investorPin', 17, 36, 36, 17, 1, 0, 0, 193);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 3, 'SecurityId', 'x._securityId', 0, 15, 15, 0, 1, 0, 1, 150);

insert into ${webmaster}.client_webwidget_columns ( widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) values ( 1,3,'Order Category', 'x.orderCategory', 1, 43, 43, 0, 1, 0 ,1, 430);

insert into ${webmaster}.client_webwidget_columns ( widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) values ( 1,3,'Strategy Id', 'x.strategyId', 1, 44, 44, 0, 1, 0 ,1, 440);

insert into ${webmaster}.client_webwidget_columns ( widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) values ( 1,3,'Order Status', 'x.orderStatus', 1, 45, 45, 0, 1, 0 ,1, 450);

insert into ${webmaster}.client_webwidget_columns ( widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) values ( 1,3,'Parent Cl Code', 'x.parentClCode', 1, 46, 46, 0, 1, 0 ,1, 460);

insert into ${webmaster}.client_webwidget_columns ( widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) values ( 1,3,'Child Cl Code', 'x.childClCode', 1, 47, 47, 0, 1, 0 ,1, 470);

insert into ${webmaster}.client_webwidget_columns ( widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) values ( 1,3,'Part Code', 'x.partCode', 1, 48, 48, 0, 1, 0 ,1, 480);

INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 3, 'Validity', 'x._orderValidity', 1, 49, 49, 9, 1, 0, 1, 490);

INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 4, 'Cash Ledger', 'x._deposit', 3, 0, 0, 0, 1, 1, 1, 10);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 4, 'Client ID', 'x._clientId', 1, 2, 2, 17, 1, 1, 1, 21);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 4, 'Cash Payin', 'x._payin', 3, 3, 3, 0, 1, 1, 1, 30);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 4, 'Cash Payout', 'x._payout', 3, 4, 4, 0, 1, 1, 1, 40);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 4, 'Adhoc Cash', 'x._adhoc', 3, 5, 5, 0, 1, 1, 1, 50);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 4, 'Option Sell Premium', 'x._optionSellPremium', 3, 7, 7, 0, 1, 1, 1, 70);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 4, 'Equity Margin', 'x._equityMarginUtilized', 3, 8, 8, 0, 1, 0, 1, 80);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 4, 'Derivative Margin', 'x._derivativeMarginUtilized', 3, 9, 9, 0, 1, 0, 1, 90);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 4, 'Cash Utilised', 'x._marginUtilized', 3, 10, 10, 0, 1, 0, 1, 100);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 4, 'M2M Loss/Profit', 'x._mtm', 3, 11, 11, 0, 1, 0, 1, 110);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 4, 'Booked Loss/Profit', 'x._bookedProfitLoss', 3, 12, 12, 0, 1, 0, 1, 120);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 4, 'Cash Available', 'x._cashAvailable', 3, 13, 13, 0, 1, 0, 1, 130);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 4, 'Credit For Sale', 'x._calculatedCreditForSale', 3, 6, 6, 0, 1, 1, 1, 60);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 4, 'Gross Commission', 'x.grossCommission', 3, 14, 14, 0, 1, 0, 1, 140);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 5, 'Order ID', 'x[1]', 0, 0, 0, 0, 1, 0, 1, 10);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 5, 'Client ID', 'x[0]', 1, 4, 4, 17, 1, 1, 1, 31);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 5, 'Market', 'x[3]', 1, 1, 1, 1, 1, 1, 1, 20);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 5, 'Security Id', 'x[4]', 1, 2, 2, 0, 1, 0, 0, 21);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 5, 'Symbol', 'x[5]', 1, 3, 3, 13, 1, 1, 1, 30);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 5, 'Transaction Time', 'x[6]', 2, 10, 10, 0, 1, 0, 1, 90);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 5, 'Value', 'x[8]', 3, 7, 7, 0, 1, 0, 1, 60);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 5, 'Instrument Type', 'x[7]', 1, 5, 5, 14, 1, 1, 1, 40);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 5, 'Margin %', 'x[9]', 5, 8, 8, 0, 1, 0, 1, 70);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 5, 'Margin Blocked/Released', 'x[10]', 3, 9, 9, 0, 1, 0, 1, 80);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 5, 'Transaction Type', 'x[11]', 1, 6, 6, 10, 1, 1, 1, 50);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 5, 'Remarks', 'x[12]', 1, 11, 11, 0, 1, 0, 1, 100);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 6, 'Exchange Order ID', 'order_id', 0, 0, 0, 0, 2, 1, 1, 10);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 6, 'Exchange Time', 'to_char(exchange_time,"DD Mon YYYY HH:MI:SS AM")', 2, 1, 1, 0, 2, 1, 1, 20);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 6, 'Message', 'message', 1, 2, 2, 0, 2, 1, 1, 30);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 7, 'Symbol', 'y["symbol"]', 1, 1, 1, 13, 1, 1, 1, 20);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 7, 'ISIN', 'x.isin', 1, 0, 0, 0, 1, 0, 1, 10);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 7, 'Total Qty', 'x.totalQty', 4, 2, 2, 0, 1, 0, 1, 30);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 7, 'Available Qty', 'y["available"]', 4, 6, 6, 0, 1, 0, 1, 60);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 7, 'After Hcut Value', 'y["ahcut"]', 3, 11, 11, 0, 1, 0, 1, 110);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 7, 'markets', 'y["markets"]', 0, 12, 12, 0, 1, 0, 0, 120);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 7, 'Current Value', 'y["hvalue"]', 3, 9, 9, 0, 1, 0, 1, 90);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 7, 'Client ID', 'x.id', 1, 3, 3, 17, 1, 1, 1, 31);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 7, 'Pending Qty', 'x.pendingQty', 4, 4, 4, 0, 1, 0, 1, 40);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 7, 'Sold Qty', 'x.soldQty', 4, 5, 5, 0, 1, 0, 1, 50);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 7, 'Source', 'x.holdSrc', 1, 7, 7, 15, 1, 1, 1, 70);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 7, 'Close Price', 'x.closePrice', 3, 8, 8, 0, 1, 0, 1, 80);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 7, 'Open Price', 'x.openPrice', 3, 14, 14, 0, 1, 0, 1, 140);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 7, 'Profit Loss', 'x.profitLoss', 3, 16, 16, 0, 1, 0, 1, 160);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 7, 'Current Market Price', 'x.currMktPrice', 3, 17, 17, 0, 1, 0, 1, 170);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 7, 'Investment Value', 'x.investmentValue', 3, 15, 15, 0, 1, 0, 1, 150);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 7, 'Hcut %', 'x.haircut', 5, 10, 10, 0, 1, 0, 1, 100);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 7, 'marketid', 'x.marketId', 1, 13, 13, 0, 1, 0, 0, 130);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (0, 6, 'Name', 'sm.symbol', 1, 0, 0, 0, 2, 1, 1, 10);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (0, 6, 'Current', 'cq.last_trade_price', 3, 1, 1, 0, 2, 1, 1, 20);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (0, 6, 'Market', 'sm.market_id', 1, 2, 2, 0, 2, 1, 1, 30);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (0, 6, 'Security', 'sm.security_id', 1, 3, 3, 0, 2, 1, 1, 40);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 8, 'Market', 'market', 1, 0, 0, 1, 2, 0, 1, 10);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 8, 'Security', 'security', 0, 1, 1, 0, 2, 0, 1, 20);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 8, 'Symbol', 'symbol', 1, 2, 2, 13, 2, 0, 1, 21);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 8, 'Hedge To', '', 0, 3, 3, 0, 0, 0, 1, 25);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 8, 'Hedge With', '', 0, 4, 4, 0, 0, 0, 1, 26);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 8, 'Underlying', 'underlying', 0, 5, 5, 0, 2, 0, 0, 27);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 8, 'Quantity', 'quantity', 4, 6, 6, 0, 2, 0, 1, 30);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 8, 'Buy/Sell', 'side', 1, 7, 7, 8, 2, 0, 1, 40);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 8, 'Instrument Type', 'type', 1, 8, 8, 2, 2, 0, 1, 50);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 8, 'Strike Price', 'strike_price', 3, 9, 9, 0, 2, 0, 1, 60);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 8, 'Maturity Date', 'maturity_date', 2, 10, 10, 0, 2, 0, 1, 70);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 8, 'Average Traded Price', 'avg_traded_price', 3, 11, 11, 0, 2, 0, 1, 80);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 8, 'Delta', 'delta', 3, 12, 12, 0, 2, 0, 1, 90);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 8, 'Gamma', 'gamma', 3, 13, 13, 0, 2, 0, 1, 100);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 8, 'Vega', 'vega', 3, 14, 14, 0, 2, 0, 1, 110);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 8, 'Theta', 'theta', 3, 15, 15, 0, 2, 0, 1, 120);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 8, 'Implied Volatility', 'implied_volatility', 3, 16, 16, 0, 2, 0, 1, 130);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 8, 'Suggestions', '', 0, 17, 17, 0, 0, 0, 1, 140);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 9, 'Client ID', 'x._clientId', 1, 0, 0, 1, 1, 1, 1, 10);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 9, 'Market', 'x._marketId', 1, 1, 1, 1, 1, 0, 1, 20);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 9, 'Security Id', 'x._securityId', 0, 2, 2, 0, 1, 0, 1, 21);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 9, 'Performed By', 'x._performedBy', 0, 3, 3, 0, 1, 0, 1, 22);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 9, 'Time', 'x.dateTime', 2, 4, 4, 0, 1, 0, 1, 23);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 9, 'Instrument Type', 'x._instrumentType', 1, 5, 5, 2, 1, 1, 1, 30);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 9, 'Symbol', 'x._scripName', 1, 6, 6, 0, 1, 1, 1, 40);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 9, 'Old Product', 'x._oldProduct', 1, 7, 7, 6, 1, 1, 1, 50);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 9, 'New Product', 'x._newProduct', 1, 9, 9, 6, 1, 1, 1, 70);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 9, 'Qty Converted', 'x._qtyConverted', 4, 11, 11, 0, 1, 0, 1, 90);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 9, 'Margin Affected', 'x._marginAffected', 3, 12, 12, 0, 1, 0, 1, 100);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 9, 'Status', 'x._status', 0, 13, 13, 20, 1, 1, 1, 110);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 9, 'Message', 'x._message', 1, 14, 14, 0, 1, 0, 1, 120);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 9, 'Mode', 'x._mode', 0, 15, 15, 8, 1, 1, 1, 130);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 10, 'Exchange', 'x._exchangeName', 1, 0, 0, 1, 2, 1, 1, 10);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 10, 'Segment', 'x._segment', 1, 1, 1, 12, 2, 1, 1, 20);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 10, 'Security ID', 'x._securityId', 0, 2, 2, 0, 2, 0, 1, 30);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 10, 'Symbol', 'x._symbol', 1, 3, 3, 13, 2, 1, 1, 40);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 10, 'Group', 'x._groupName', 1, 4, 4, 0, 2, 1, 1, 50);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 10, 'Description', 'x._companyName', 1, 5, 5, 0, 2, 0, 1, 60);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 10, 'ISIN', 'x._isin', 1, 6, 6, 0, 2, 0, 1, 70);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 10, 'VAR %', 'x._var', 5, 7, 7, 0, 2, 0, 1, 80);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 10, 'ELM %', 'x._elm', 5, 8, 8, 0, 2, 0, 1, 90);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 10, 'Haircut %', 'x._haircut', 5, 9, 9, 0, 2, 0, 1, 100);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 11, 'Market', 'x._market', 1, 0, 0, 1, 2, 1, 1, 10);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 11, 'Security ID', 'x._securityId', 0, 1, 1, 0, 2, 0, 1, 20);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 11, 'Symbol', 'x._symbol', 1, 2, 2, 13, 2, 1, 1, 30);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 11, 'Instrument Type', 'x._instrumentType', 1, 3, 3, 2, 1, 1, 1, 40);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 11, 'Product', 'x._product', 1, 4, 4, 6, 1, 1, 1, 50);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 11, 'Price', 'x._price', 3, 5, 5, 0, 1, 0, 1, 60);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 11, 'Open Qty', 'x._buyQuantity-x._sellQuantity', 4, 6, 6, 0, 1, 0, 1, 70);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 11, 'Margin %', 'x._margin', 5, 8, 8, 0, 1, 0, 1, 90);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 11, 'LTP', 'x._ltp', 3, 9, 9, 0, 1, 0, 1, 100);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 11, 'M2M Profit/Loss', 'x._mtm', 3, 10, 10, 0, 1, 0, 1, 110);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 12, 'Market', 'x._market', 1, 0, 0, 1, 2, 1, 1, 10);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 12, 'Symbol', 'x._symbol', 1, 1, 1, 13, 2, 1, 1, 20);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 12, 'Maturity Date', 'x._maturityDate', 1, 2, 2, 0, 2, 0, 1, 30);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 12, 'Market Lot', 'x._marketLot', 0, 3, 3, 0, 2, 0, 1, 40);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 12, 'Span %', 'x._span', 5, 4, 4, 0, 2, 0, 1, 50);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 12, 'Exposure %', 'x._exposure', 5, 5, 5, 0, 2, 0, 1, 60);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 12, 'Total Margin %', 'x._totalMargin', 5, 6, 6, 0, 2, 0, 1, 70);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 12, 'Span Margin per Lot', 'x._spanMarginLot', 5, 7, 7, 0, 2, 0, 1, 80);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 12, 'Exposure Margin per Lot', 'x._exposureMarginLot', 5, 8, 8, 0, 2, 0, 1, 90);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 12, 'Total Margin per Lot', 'x._totalMarginLot', 5, 9, 9, 0, 2, 0, 1, 100);
INSERT INTO ${webmaster}.client_webwidget_columns (widget_category, widget_number, display_name, column_name, data_type, default_order, user_order, acronym_number, from_database, filtersignal, showmanage, actual_order) VALUES (1, 12, 'Net Future Value', 'x._netFuture', 5, 10, 10, 0, 2, 0, 1, 110);


--
-- Data for Name: ${webmaster}.web_widget_list; Type: TABLE DATA; Schema: ${webmaster}; Owner: mutrade
--

INSERT INTO ${webmaster}.web_widget_list (wname, category, wnumber, show_widget, widget_id) VALUES ('News', 0, 4, 1, 2);
INSERT INTO ${webmaster}.web_widget_list (wname, category, wnumber, show_widget, widget_id) VALUES ('Tweets', 0, 5, 1, 5);
INSERT INTO ${webmaster}.web_widget_list (wname, category, wnumber, show_widget, widget_id) VALUES ('Order Depth', 0, 2, 1, 12);
INSERT INTO ${webmaster}.web_widget_list (wname, category, wnumber, show_widget, widget_id) VALUES ('Margin Summary', 1, 4, 1, 4);
INSERT INTO ${webmaster}.web_widget_list (wname, category, wnumber, show_widget, widget_id) VALUES ('Order Book', 1, 2, 1, 6);
INSERT INTO ${webmaster}.web_widget_list (wname, category, wnumber, show_widget, widget_id) VALUES ('Market Watch', 1, 0, 1, 7);
INSERT INTO ${webmaster}.web_widget_list (wname, category, wnumber, show_widget, widget_id) VALUES ('Position', 1, 1, 1, 8);
INSERT INTO ${webmaster}.web_widget_list (wname, category, wnumber, show_widget, widget_id) VALUES ('Trade Book', 1, 3, 1, 9);
INSERT INTO ${webmaster}.web_widget_list (wname, category, wnumber, show_widget, widget_id) VALUES ('Buy/Sell', 0, 1, 1, 10);
INSERT INTO ${webmaster}.web_widget_list (wname, category, wnumber, show_widget, widget_id) VALUES ('Holdings', 1, 7, 1, 13);
INSERT INTO ${webmaster}.web_widget_list (wname, category, wnumber, show_widget, widget_id) VALUES ('Pivot Point', 0, 7, 1, 14);
INSERT INTO ${webmaster}.web_widget_list (wname, category, wnumber, show_widget, widget_id) VALUES ('Product Conversion Summary', 1, 9, 1, 16);
INSERT INTO ${webmaster}.web_widget_list (wname, category, wnumber, show_widget, widget_id) VALUES ('Risk Assessment', 1, 11, 1, 17);
INSERT INTO ${webmaster}.web_widget_list (wname, category, wnumber, show_widget, widget_id) VALUES ('Risk Tools', 1, 10, 1, 18);
INSERT INTO ${webmaster}.web_widget_list (wname, category, wnumber, show_widget, widget_id) VALUES ('Price Alert Widget', 0, 16, 1, 21);
