insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26000, 'Nifty 50', 'NIFTY50');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26013, 'Nifty Next 50', 'NIFTYNEXT50');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26012, 'Nifty 100', 'NIFTY100');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26033, 'Nifty 200', 'NIFTY200');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26006, 'Nifty 500', 'NIFTY500');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26040, 'Nifty100 Liq 15', 'Nifty100LIQ15');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26011, 'Nifty Midcap 100', 'NIFTYMIDCAP100');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26014, 'Nifty Midcap 50', 'NFTYMCAP50');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26029, 'Nifty Auto', 'NIFTYAUTO');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26009, 'Nifty Bank', 'BANKNIFTY');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26021, 'Nifty FMCG', 'NIFTYFMCG');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26008, 'Nifty IT', 'NIFTYIT');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26031, 'Nifty Media', 'NIFTYMEDIA');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26030, 'Nifty Metal', 'NIFTYMETAL');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26023, 'Nifty Pharma', 'NIFTYPHARMA');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26025, 'Nifty PSU Bank', 'NIFTYPSUBANK');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26018, 'Nifty Realty', 'NIFTYREALTY');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26024, 'Nifty CPSE', 'NIFTYCPSE');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26020, 'Nifty Energy', 'NIFTYENERGY');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26019, 'Nifty Infra', 'NIFTYINFRA');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26036, 'Nifty Consumption', 'NIFTYCONSUMP');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26035, 'Nifty Commodities', 'NIFTYCOMMDIT');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26022, 'Nifty MNC', 'NIFTYMNC');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26041, 'Nifty50 Value 20', 'NIFTY50VALUE20');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26017, 'India VIX', 'INDIAVIX');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26016, 'HangSeng BeES-NAV', 'HNGSNGBEES');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26042, 'Nifty Div Opps 50', 'NIFTYDIVOPP50');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26044, 'Nifty Serv Sector', 'NIFTYSERVICESEC');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26045, 'Nifty Small 100', 'NIFTYSMALL100');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26028, 'S&P500', 'S&P500');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26043, 'Nifty Financial Services', 'NIFTYFINANCESER');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26001, 'Nifty Defty', 'DEFTY');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26032, 'Nifty Smallcap', 'NIFTYSMALCAP');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26037, 'Nifty Finance', 'NIFTYFINANCE');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26026, 'Nifty Service', 'NIFTYSERVICE');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26034, 'Nifty Dividend Oppt', 'NIFTYDIVOPPT');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26038, 'Nifty Dividend', 'NIFTYDIVND');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26039, 'FTSE 100', 'FTSE100');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26027, 'Dow Jones Ind Avg', 'DJIA');
insert into ${appmaster}.indices values ('DEFAULT','NSECM', 26046, 'Nifty PSE', 'NIFTYPSE');
insert into ${appmaster}.indices values ('DEFAULT','BSECM', 1, 'BSE sensitive index', 'SENSEX');
insert into ${appmaster}.indices values ('DEFAULT','BSECM', 2, 'BSE 100 scrips index', 'BSE100');
insert into ${appmaster}.indices values ('DEFAULT','BSECM', 3, 'BSE 200 scrips index', 'BSE200');
insert into ${appmaster}.indices values ('DEFAULT','BSECM', 4, 'BSE 500 scrips index', 'BSE500');
insert into ${appmaster}.indices values ('DEFAULT','BSECM', 5, 'BSE Information Technology Index', 'BSE IT');
insert into ${appmaster}.indices values ('DEFAULT','BSECM', 6, 'BSE Fast Moving Consumer Goods Index', 'BSEFMC');
insert into ${appmaster}.indices values ('DEFAULT','BSECM', 7, 'BSE Capital Goods Index', 'BSE CG');
insert into ${appmaster}.indices values ('DEFAULT','BSECM', 8, 'BSE Consumer Durables index', 'BSE CD');
insert into ${appmaster}.indices values ('DEFAULT','BSECM', 9, 'BSE HealthCare index', 'BSE HC');
insert into ${appmaster}.indices values ('DEFAULT','BSECM', 10, 'BSE Public Sector Unit Index', 'BSE PS');
insert into ${appmaster}.indices values ('DEFAULT','BSECM', 11, 'BSE Teck Index', 'TECK');
