 INSERT INTO ${appmaster}.permission_templates 
( id, 
  name, 
  description, 
  branch, 
  creater_branch, 
  permission_type, 
  user_type, 
  updated_by, 
  effective_time_stamp )
VALUES (  
  (SELECT (coalesce(MAX(id), 0) + 1) FROM ${appmaster}.permission_templates),
  'ALL',
  'Default permissions template', 
  'ROOTBRANCH',   
  'ROOTBRANCH',
  1,     
  1,
  '',
  now() );

/* for action_id  = 7, 24, 25 accessMode =  2 [3 = writemode , 2 = readMode ] */

INSERT INTO ${appmaster}.permission_template_details
( template_id, action_id, access_mode, updated_by, effective_time_stamp )
VALUES ( (SELECT (coalesce(MAX(id), 1)) FROM ${appmaster}.permission_templates),
  1, 3, '', now() ),
( (SELECT (coalesce(MAX(id), 1)) FROM ${appmaster}.permission_templates),
  3, 3, '', now() ),
( (SELECT (coalesce(MAX(id), 1)) FROM ${appmaster}.permission_templates),
  4, 3, '', now() ),
( (SELECT (coalesce(MAX(id), 1)) FROM ${appmaster}.permission_templates),
  5, 3, '', now() ),
( (SELECT (coalesce(MAX(id), 1)) FROM ${appmaster}.permission_templates),
  6, 3, '', now() ),
( (SELECT (coalesce(MAX(id), 1)) FROM ${appmaster}.permission_templates),
  7, 2, '', now() ),
( (SELECT (coalesce(MAX(id), 1)) FROM ${appmaster}.permission_templates),
  8, 3, '', now() ),
( (SELECT (coalesce(MAX(id), 1)) FROM ${appmaster}.permission_templates),
  9, 3, '', now() ),
( (SELECT (coalesce(MAX(id), 1)) FROM ${appmaster}.permission_templates),
  11, 3, '', now() ),
( (SELECT (coalesce(MAX(id), 1)) FROM ${appmaster}.permission_templates),
  12, 3, '', now() ),
( (SELECT (coalesce(MAX(id), 1)) FROM ${appmaster}.permission_templates),
  13, 3, '', now() ),
( (SELECT (coalesce(MAX(id), 1)) FROM ${appmaster}.permission_templates),
  15, 3, '', now() ),
( (SELECT (coalesce(MAX(id), 1)) FROM ${appmaster}.permission_templates),
  16, 3, '', now() ),
( (SELECT (coalesce(MAX(id), 1)) FROM ${appmaster}.permission_templates),
  17, 3, '', now() ),
( (SELECT (coalesce(MAX(id), 1)) FROM ${appmaster}.permission_templates),
  18, 3, '', now() ),
( (SELECT (coalesce(MAX(id), 1)) FROM ${appmaster}.permission_templates),
  19, 3, '', now() ),
( (SELECT (coalesce(MAX(id), 1)) FROM ${appmaster}.permission_templates),
  20, 3, '', now() ),
( (SELECT (coalesce(MAX(id), 1)) FROM ${appmaster}.permission_templates),
  21, 3, '', now() ),
( (SELECT (coalesce(MAX(id), 1)) FROM ${appmaster}.permission_templates),
  22, 3, '', now() ),
( (SELECT (coalesce(MAX(id), 1)) FROM ${appmaster}.permission_templates),
  23, 3, '', now() ),
( (SELECT (coalesce(MAX(id), 1)) FROM ${appmaster}.permission_templates),
  24, 2, '', now() ),
( (SELECT (coalesce(MAX(id), 1)) FROM ${appmaster}.permission_templates),
  25, 2, '', now() );

