delete from ${appmaster}.indices where market_id = 'BSECM';
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 1, 'SENSEX', 'SENSEX');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 2, 'BSE100', 'BSE100');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 3, 'BSE200', 'BSE200');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 4, 'BSE500', 'BSE500');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 34, 'BSE IT', 'BSE IT');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 32, 'BSEFMC', 'BSEFMC');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 7, 'BSE CG', 'BSE CG');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 8, 'BSE CD', 'BSE CD');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 33, 'BSE HC', 'BSE HC');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 10, 'BSE PSU', 'BSE PSU');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 11, 'TECK', 'TECK');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 12, 'BANKEX', 'BANKEX');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 13, 'AUTO', 'AUTO');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 14, 'METAL', 'METAL');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 15, 'OILGAS', 'OILGAS');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 30, 'MIDCAP', 'MIDCAP');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 31, 'SMLCAP', 'SMLCAP');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 18, 'DOL30', 'DOL30');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 19, 'DOL100', 'DOL100');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 20, 'DOL200', 'DOL200');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 21, 'REALTY', 'REALTY');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 22, 'POWER', 'POWER');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 23, 'BSEIPO', 'BSEIPO');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 25, 'GREENX', 'GREENX');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 26, 'CARBON', 'CARBON');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 27, 'SMEIPO', 'SMEIPO');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 28, 'INFRA', 'INFRA');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 29, 'CPSE', 'CPSE');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 35, 'MFG', 'MFG');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 36, 'ALLCAP', 'ALLCAP');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 37, 'BASMTR', 'BASMTR');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 38, 'CDGS', 'CDGS');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 39, 'ENERGY', 'ENERGY');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 40, 'FIN', 'FIN');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 41, 'INDSTR', 'INDSTR');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 42, 'LRGCAP', 'LRGCAP');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 43, 'MIDSEL', 'MIDSEL');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 44, 'SMLSEL', 'SMLSEL');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 45, 'TELCOM', 'TELCOM');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 46, 'UTILS', 'UTILS');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 47, 'SNSX50', 'SNSX50');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 48, 'SNXT50', 'SNXT50');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 49, 'BHRT22', 'BHRT22');
insert into ${appmaster}.indices values ('DEFAULT', 'BSECM', 50, 'ESG100', 'ESG100');
